spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWK_URL}
  rabbitmq:
    addresses: ${RABBIT_URL}

  cloud:
    stream:
      function:
        definition: generate
        bindings:
          getRsiPilotInfo-out-0.destination: pilot-info-events
        source: getRsiPilotInfo

authorities: {'access': 'scope', 'user': 'cognito:groups'}



