spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWK_URL}
  rabbitmq:
    host:
    exchange:
      verify: rsi-verify
      auth: rsi-auth
      pilot: pilot-info-events
    queue:
      verify: rsi-verify.v1-send-verify
      auth: v1-auth-status
    routingkey: "#"
    password:
    username:
    virtual-host: ${VIRTUAL}
    ssl:
      enabled: true

authorities: { 'access': 'scope', 'user': 'cognito:groups' }

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT}



