spring:
  data:
    mongodb:
      uri: ""
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWK_URL}
  rabbitmq:
    addresses:

  cloud:
    stream:
      function:
        definition: generate
        bindings:
          getRsiPilotInfo-out-0.destination: pilot-info-events
        source: getRsiPilotInfo



